# DO NOT DELETE THIS LINE
config-version: '2.0'

# ******************************************************
# * Chatty
#   Universal chat-system for Bukkit-server.
#
#   Creator: MrBrikster
#
# * Optional dependencies:
#   Vault, PlaceholderAPI, NameTagEdit.
# ******************************************************

# * GENERAL
general:
  # Plugin localization.
  #
  # en - English.
  # ru - Russian.
  # de - German.
  # zh_CN - Simplified Chinese
  locale: en

  # Chat listener priority.
  # Possible values:
  # lowest, low, normal, high, highest.
  priority: low

  # Chat logging in "plugins/Chatty/logs/".
  log: true

  # Completely cancels chat events,
  # if it cancelled by moderation method
  # (instead of clearing recipients).
  completely-cancel: false

  # Keep recipients list from previous listeners.
  # Useful if you have some plugins, that changes recipients list, and Chatty ignores it
  # (for example, Chatty may corrupt "/ignore" command of EssentialsX).
  #
  # Default: true
  keep-old-recipients: true

  # Hides vanished players from recipients (and sends "no-recipients" message when all recipients are vanished)
  # Supports EssentialsX, SuperVanish, PremiumVanish, VanishNoPacket etc.
  # Default: false
  hide-vanished-recipients: true

  # Storage player data mode.
  # true - data will store by UUIDs.
  # false - data will store by nicknames.
  uuid: false

  # Enables support for "-3" chat range.
  # Messages from that chats will be sent to all BungeeCord servers with Chatty.
  #
  # Notes:
  # * Console logs will not prints on empty BungeeCord servers (non-fixable)
  # * So Chatty send message to another server, there must be chat with the same name and range -3.
  bungeecord: false

# * CHATS
#
# On the server there can be different chats with different settings,
# whether it's donate-chat, admin-chat, or the usual local and global.
#
# Permissions:
# chatty.chat.<chat> - permission for both writing and seeing messages.
# chatty.chat.<chat>.write - permission for writing messages.
# chatty.chat.<chat>.see - permission for seeing messages.
#
# Chat has the following options:
# *enable*       - on/off chat.
# *display-name* - name of chat, displaying in placeholders and locale messages. Default: regular name of chat.
# *format*       - chat format string.
# *range*        - chat range. -1 to world-wide chat, -2 to server-wide, -3 to BungeeCord-wide chat.
# *symbol*       - character from which message should begin.
# *cooldown*     - message cooldown in seconds (bypass permission - chatty.cooldown.<chat>).
# *money*        - message price (depends on Vault).
# *permission*   - check permissions for this chat? Default: true.
# *command*      - Command that is used to switch to chat to use it by default if symbol is not specified. Default: empty.
# *aliases*      - Aliases for command. Default: empty.
chats:
  local:
    enable: true
    display-name: 'Local'
    format: '&e[&6Local&e] &r{prefix}{player}{suffix}&8: &f{message}'
    range: 100
    cooldown: -1
    command: 'localchat'
    aliases: [ 'lchat' ]

  global:
    enable: true
    display-name: 'Global'
    format: '&e[&aGlobal&e] &r{prefix}{player}{suffix}&8: &f{message}'
    range: -1
    symbol: '!'
    cooldown: -1
    command: 'globalchat'
    aliases: [ 'gchat' ]

  # Example chat with multiline format
  notify:
    enable: true
    format: |

      &7==========================================
        &c{player}&8: &7{message}
      &7==========================================
    range: -3
    symbol: '$'
    cooldown: -1

    # Plays sound for all chat recipients
    sound: CLICK

    # Disables some moderation methods for this chat
    moderation:
      caps: false
      swear: false
      advertisement: false

    # Disables spy-mode for this chat
    spy: false

# * PRIVATE MESSAGING
pm:
  # Enables private messaging function.
  enable: true

  # Allows console to messaging players
  # and messaging players to console.
  # Default: false
  allow-console: false

  # Allows to PM players, that in vanish
  # Supports EssentialsX, SuperVanish, PremiumVanish, VanishNoPacket etc.
  # Default: true
  allow-pm-vanished: false

  # Format of messages
  #
  # Variables:
  # {sender-name}, {recipient-name} - nicknames of sender and recipient.
  # {sender-prefix}, {recipient-prefix} - prefixes of sender and recipient.
  # {sender-suffix}, {recipient-suffix} - suffixes of sender and recipient.
  # {message} - private message.
  format:
    recipient: '&7{sender-prefix}{sender-name} &6-> &7{recipient-prefix}{recipient-name}: &f{message}'
    sender: '&7{sender-prefix}{sender-name} &6-> &7{recipient-prefix}{recipient-name}: &f{message}'

  commands:
    msg:
      # Enables "/msg" command.
      # Permission: chatty.command.msg
      enable: true
      # Aliases for "/msg" command.
      aliases: [ 'message', 'pm', 'm', 'whisper', 'w', 'tell', 't' ]

    # To keep compatibility with EssentialsX
    # main name of command is "/r".
    reply:
      # Enables "/r" command.
      # Permission: chatty.command.reply
      enable: true
      # Aliases for "/r" command.
      aliases: [ 'reply' ]

    ignore:
      # Enables "/ignore" command.
      # Permission: chatty.command.ignore
      enable: true
      # Aliases for "/ignore" command.
      aliases: [ ]

# * SPY
#
# Mode for spying for chat and private messages.
spy:
  enable: true

  # Spy-mode message format.
  format:
    # Permission: chatty.spy.<chat>
    chat: '&6[Spy] &r{format}'

    # Permission: chatty.spy.pm
    #
    # Uses sender format of PM.
    # Supports variables:
    # {format}, {sender-prefix}, {sender-name}, {sender-suffix},
    # {recipient-prefix}, {recipient-name}, {recipient-suffix}, {message}
    pm: '&6[Spy] &r{format}'

# * JSON
#
# Chat formatting with additional interactive features.
#
# 1.7.10 and newer.
json:
  enable: false

  # Command or text that executes (by player) when you click on the player's name.
  #
  # *** You can use EITHER "command" OR "suggest" OR "link".
  #
  # Supports PlaceholderAPI.
  # You can use "{player}" variable here.
  command: /home

  # Command or text that suggests when you click on the player's name.
  #
  # *** You can use EITHER "command" OR "suggest" OR "link".
  #
  # Supports PlaceholderAPI.
  # You can use "{player}" variable here.
  suggest: '/msg {player} '

  # URL that opens when when you click on the player's name.
  #
  # You must use "http://" or "https://" prefix, else you will crash Minecraft client :D
  #
  # *** You can use EITHER "command" OR "suggest" OR "link".
  #
  # Supports PlaceholderAPI.
  # You can use "{player}" variable here.
  link: 'https://google.com'

  # Hover tooltip for the player's name.
  # Supports PlaceholderAPI.
  #
  # You can use "{player}" variable here.
  tooltip:
    - '&fPlayer &e{player}'
    - '&fThis tooltip supports'
    - '&fPlaceholderAPI placeholders!'

  # Mentions.
  # "@nickname" will notify player that he's mentioned.
  # Also it will replaced to a clickable JSON-part.
  #
  # Requires permission: chatty.mentions
  mentions:
    enable: true

    # Display format of mention.
    format: '&e&l@{player}'

    # Plays sound to player, that was mentioned.
    # Remove the line if not needed.
    sound: CLICK

    # Sound volume and pitch parameters
    sound-volume: 1.0
    sound-pitch: 1.0

    # Allows to mention vanished players
    # Default: true
    allow-vanished: false

    # Command or text that executes (by player) when you click on the mention.
    #
    # *** You can use EITHER "command" OR "suggest" OR "link".
    #
    # Supports PlaceholderAPI.
    # You can use "{player}" variable here.
    command: /home

    # Command or text that suggests when you click on the mention.
    #
    # *** You can use EITHER "command" OR "suggest" OR "link".
    #
    # Supports PlaceholderAPI.
    # You can use "{player}" variable here.
    suggest: '/msg {player} '

    # URL that opens when when you click on the mention.
    #
    # You must use "http://" or "https://" prefix, else you will crash Minecraft client :D
    #
    # *** You can use EITHER "command" OR "suggest" OR "link".
    #
    # Supports PlaceholderAPI.
    # You can use "{player}" variable here.
    link: 'https://example.com/players?name={player}'

    # Hover tooltip for the mention.
    # Supports PlaceholderAPI.
    #
    # You can use "{player}" variable here.
    tooltip:
      - '&fClick here to message &e{player}'

  # Swears hovers.
  #
  # Available properties:
  # tooltip, suggest
  #
  # Permission: chatty.swears.see
  swears:
    enable: true
    tooltip:
      - '&o{word}'
      - ''
      - '&eClick here to add word to whitelist.'
    suggest: /swears add {word}

  # Replacements for chat formats.
  #
  # You can replace some plain text with clickable parts
  # to make chat more interactive.
  #
  # Available properties:
  # text, tooltip, command, suggest, link.
  replacements:
    'Admin':
      # Original text.
      original: '&cAdmin'

      # New text.
      #
      # Supports PlaceholderAPI.
      # You can use "{player}" variable here.
      #
      # Remove this line, if you need original text.
      text: '&cAdmin'

      # Hover tooltip for the text.
      #
      # Supports PlaceholderAPI.
      #
      # You can use "{player}" variable here.
      tooltip:
        - '&cThis is admin.'
        - '&4&lBe afraid of him!'
        - ''
        - '&eClick here to see the server rules.'

      # *** You should use "command" OR "suggest-command" OR "link" and cannot combine.
      # Command that executes when you click on the text.
      #
      # Supports PlaceholderAPI.
      #
      # You can use "{player}" variable here.
      command: /rules

# * NOTIFICATIONS
#
# There are four types of notifications:
# via Chat, Title (1.8.8 and newer), ActionBar (1.8.8 and newer) and Advancements (1.12 and newer).
notifications:
  # Chat notifications.
  chat:
    # On/off chat notifications.
    enable: true

    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.chat.default
      default:
        # Messages interval.
        time: 60

        # Messages prefix.
        prefix: ''

        # List of messages.
        # Supports PlaceholderAPI.
        # Supports JSON formatting.
        #
        # Notification messages are using "/tellraw" JSON format.
        # For example: {"text":"","extra":[{"text":"Try to search it with ","color":"white"},{"text":"search system","color":"yellow","clickEvent":{"action":"open_url","value":"http://google.com"},"hoverEvent":{"action":"show_text","value":"Search it in Google"}}]}
        # This JSON will be a message "Try to search it with search system" with hover and clickable text
        messages:
          - '&cThe server is using Chatty!\n&aOur address: 127.0.0.1\n&aVisit out site: example.com'
          - '&aThe server is using Chatty!'

        # Permission for seeing notification.
        # Default: true
        permission: false

        # Show messages in random order.
        # Default: false
        random: true

  # ActionBar notifications.
  # It's static notifications,
  # which changes the message with interval.
  #
  # Permission: chatty.notification.actionbar
  actionbar:
    # On/off ActionBar notifications.
    # Only 1.8+.
    enable: false

    # One message time.
    time: 60

    # Messages prefix.
    prefix: ''

    # List of messages.
    # Supports PlaceholderAPI.
    messages:
      - '&cThe server is using Chatty!'
      - '&aThe server is using Chatty!'

    # Permission for seeing notification.
    # Default: true
    permission: false

    # Show messages in random order.
    # Default: false
    random: true

  # Title notifications.
  title:
    # On/off title notifications.
    enable: true

    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.title.default
      default:
        # Messages interval.
        time: 60

        # List of messages.
        # Supports PlaceholderAPI.
        messages:
          - |
            &cThe server is using Chatty!
            &eOur address: 127.0.0.1
          - '&aThe server is using Chatty!'

        # Permission for seeing notification.
        # Default: true
        permission: false

        # Show messages in random order.
        # Default: false
        random: false

  # Advancements (Achievements) notifications.
  advancements:
    # Advancements notifications.
    # Only 1.12 and newer.
    enable: false
    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.advancements.default
      default:
        # Messages interval.
        time: 60

        # List of messages.
        messages:
          - icon: 'minecraft:diamond'
            header: '&bChatty'
            footer: '&fThank you for using!'
          - icon: 'minecraft:gold_ingot'
            header: '&eChatty'
            footer: '&fThank you for using!'

        # Permission for seeing notification.
        # Default: true
        permission: false

        # Show messages in random order.
        # Default: false
        random: false

# * MODERATION
#
# Automatic chat moderation tools.
# Works with private messages.
moderation:
  caps:
    # On/off caps protection.
    # Bypass permission: chatty.moderation.caps
    enable: true

    # Minimal length of message to caps checking.
    length: 6

    # Minimal upper case percent for caps.
    percent: 80

    # On/off caps message blocking.
    # When false, message will be sent in lower case.
    block: true

  advertisement:
    # On/off advertisement protection.
    # Bypass permission: chatty.moderation.advertisement
    enable: true

    # Regular expressions for IP-addresses and websites.
    patterns:
      ip: '\b((\d{1,2}|2(5[0-5]|[0-4]\d))[._,)(-]+){3}(\d{1,2}|2(5[0-5]|[0-4]\d))(:\d{2,7})?'
      web: '(?i)\b(https?:\/\/)?[\w\.а-яА-Я-]+\.([a-z]{2,4}|[рР][фФ]|[уУ][кК][рР])\b(:\d{2,7})?(\/\S+)?'

    # On/off advertisement message blocking.
    # When false, advertisement will be replaced.
    block: true

    # Replacement for advertisement.
    replacement: '<advertisement>'

    # Whitelisted IP-addresses and sites.
    whitelist:
      - 'example.com'
      - 'vk.com'
      - 'google.com'
      - 'youtube.com'
      - 'yandex.ru'
      - '192.168.1.1'
      - '127.0.0.1'

  swear:
    # On/off swear protection.
    # Bypass permission: chatty.moderation.swear
    enable: false

    # On/off swear message blocking.
    # When false, swears will be replaced.
    block: true

    # Replacement for swears.
    replacement: '<swear>'
    # Files with swears are located at "Chatty/swears"

# * MISCELLANEOUS
miscellaneous:
  commands:
    # Used to switch default chat (when symbol is not specified): /chat <chat>
    # Permission: chatty.command.chat
    chat:
      enable: true
      aliases: [ 'chats', 'switchchat' ]

    # Clear chat for yourself: /clearchat
    # Permission: chatty.command.clearchat
    #
    # Clear chat for all: /clearchat all
    # Permission: chatty.command.clearchat.all
    clearchat:
      enable: true
      aliases: [ 'chatclear' ]

    # Change chat (and NametagEdit, if enabled) prefix
    # /prefix <player> <prefix>
    #
    # Permissions:
    # chatty.command.prefix
    # chatty.command.prefix.others
    prefix:
      enable: true

      # Automatically appends a substring after prefix.
      after-prefix: ' '

      # Limits prefix length (inclusive "after-prefix")
      length-limit:
        min: 3
        max: 16

      # Auto-applying in NametagEdit.
      # (Requires NameTagEdit plugin).
      auto-nte: false

    # Change chat (and NametagEdit, if enabled) suffix
    # /suffix <player> <suffix>
    #
    # Permissions:
    # chatty.command.suffix
    # chatty.command.suffix.others
    suffix:
      enable: true

      # Automatically appends a substring before suffix.
      before-suffix: ' '

      # Limits suffix length (inclusive "before-suffix")
      length-limit:
        min: 3
        max: 16

      # Auto-applying in NametagEdit.
      # (Requires NameTagEdit plugin).
      auto-nte: false

  # Change vanilla Minecraft messages.
  # Supports PlaceholderAPI.
  vanilla:
    join:
      enable: true

      # Set to '' if you want to make it hidden.
      message: '&8> &e{prefix}{player}{suffix} &ejoined the server.'

      # Plays sound to all, when player joins.
      # Remove the line if not needed.
      sound: ORB_PICKUP

      # Sound volume and pitch parameters
      sound-volume: 1.0
      sound-pitch: 1.0

      # Permission: chatty.misc.joinmessage
      # Default: true
      permission: false

      # Specified parameters for the first join
      first-join:
        # First join message.
        # Set to '' if you don't want to see special message for the first join.
        message: '&8> &e{prefix}{player}{suffix} &6joined the server for the first time!'
        # Plays sound to all, when player joins.
        # Remove the line if not needed.
        sound: ORB_PICKUP

        # Sound volume and pitch parameters
        sound-volume: 1.0
        sound-pitch: 1.0

    quit:
      enable: true

      # Set to '' if you want to make it hidden.
      message: '&8> &e{prefix}{player}{suffix} &eleft the server.'

      # Plays sound to all, when player quits.
      # Remove the line if not needed.
      sound: ORB_PICKUP

      # Sound volume and pitch parameters
      sound-volume: 1.0
      sound-pitch: 1.0

      # Permission: chatty.misc.quitmessage
      # Default: true
      permission: false

    death:
      enable: true

      # Set to '' if you want to make it hidden.
      message: '&8> &e{prefix}{player}{suffix} &edied.'

      # Plays sound to all, when player dies.
      # Remove the line if not required.
      sound: BAT_DEATH

      # Sound volume and pitch parameters
      sound-volume: 1.0
      sound-pitch: 1.0

      # Permission: chatty.misc.deathmessage
      # Default: true
      permission: false
