# GENERAL
# Priority: priority of event handler:
# lowest, low, normal, high or highest.
#
# Log: save logs of chat?
#
# Spy: sends all messages to players with "chatty.spy" permission.
# Format: format of spy messages.
general:
  priority: low
  log: true
  spy:
    enable: true
    format: '&6[Spy] &r{format}'

# CHAT MODES
# You need to enable at least one.
#
# Range: range of chat in blocks.
# -1 to world-wide chat.
# -2 to server-wide chat.
#
# Symbol: symbol to use this chat.
# Empty symbol to set the chat as default.
#
# Cooldown: cooldown for this chat in seconds.
#
# ******************************************
# You can create any types of chats, not only "local" or "global".
chats:
  # Local chat.
  # Permissions:
  # chatty.chat.local.see, chatty.chat.local.send
  # or chatty.chat.local
  local:
    enable: true
    format: '[Local] {prefix}{player}{suffix}: {message}'
    range: 100
    symbol: ''
    cooldown: -1

  # Global chat.
  # chatty.chat.global.see, chatty.chat.global.send
  # or chatty.chat.global
  global:
    enable: true
    format: '[Global] {prefix}{player}{suffix}: {message}'
    range: -1
    symbol: '!'
    cooldown: -1

    # Required money for one message
    #
    # Depends on Vault
    money: 100

# COMMANDS
# Settings for command groups
#
# Triggers types:
# CONTAINS ABCD
# STARTS ABCD
# COMMAND ABCD
#
# Bypass permission: chatty.commands.<command-group>
commands:
  anti-hack:
    triggers:
    - 'CONTAINS :'
    block: true
    message: 'You can''t use commands with ":" symbol.'
  plugins-hiders:
    triggers:
    - 'COMMAND pl'
    - 'COMMAND plugins'
    block: true
    message: '&fPlugins (1): &aWorldGuard'
  spawn-cooldown:
    triggers:
    - 'COMMAND spawn'
    - 'COMMAND home'
    cooldown: 15
    message: '&cPlease, wait {cooldown} seconds before using this command again.'

# ANNOUNCEMENTS
# Messages in new "Advancements" notifications
#
# WARNING: 1.12 and higher.
announcements:
  enable: false
  # Repeating time in seconds.
  time: 60
  list:
  - icon: 'minecraft:cobblestone'
    header: '&6Header'
    footer: '&7Message text #1'
  - icon: 'minecraft:apple'
    header: '&6Header'
    footer: '&7Message text #2'

# ALERTS
# Messages in chat
alerts:
  enable: true
  lists:
    # Permission to see: chatty.alerts.default
    default:
      # Repeating time in seconds.
      time: 60
      # Prefix for messages
      prefix: ''
      messages:
      - '&7Message text &c#1'
      - '&7Message text &a#2'

# ANTI-ADS
# Hides messages with ads for other players
anti-ads:
  enable: true
  whitelist:
  - 'example.com'
  - 'vk.com'
  - 'google.com'
  - '192.168.1.1'
  - '127.0.0.1'

# MESSAGES
messages:
  no-chat-mode: '&cApplicable chat-mode not found. You can''t send the message.'
  reload: '&aConfig successful reloaded!'
  no-permission: '&cYou don''t have permission.'
  spy-on: '&aYou have been enabled spy-mode.'
  spy-off: '&cYou have been disabled spy-mode.'
  cooldown: '&cWait for {cooldown} seconds, before send message in this chat again.'
  no-recipients: '&cNobody heard you.'
  ads-found: '&cYou have sent message with ads!'

