# GENERAL
# Priority: priority of event handler:
# lowest, low, normal, high or highest.
#
# Log: save logs of chat?
#
# Announcements: messages in ADVANCEMENT menu. Only for 1.12 and higher.
#
# Spy: sends all messages to players with "chatty.spy" permission.
# Format: format of spy messages.
general:
  priority: normal
  log: true
  announcements: true
  spy:
    enable: true
    format: '&6[Spy] &r{format}'

# CHAT MODES
# You need to enable at least one.
#
# Range: range of chat in blocks.
# -1 to disable.
#
# Symbol: symbol to use this chat.
# Empty symbol to set the chat as default.
#
# ******************************************
# You can create any types of chats, not only "local" or "global".
chats:
  # Local chat.
  # Permission: chatty.chat.local
  local:
    enable: true
    format: '[Local] {prefix}{player}{suffix}: {message}'
    range: 100
    symbol: ''

  # Global chat.
  # Permission: chatty.chat.global
  global:
    enable: true
    format: '[Global] {prefix}{player}{suffix}: {message}'
    range: -1
    symbol: '!'

# ANNOUNCEMENTS
# Messages in new "Advancements" notifications
#
# WARNING: 1.12.2+.
announcements:
  enable: false
  # Repeating time in seconds.
  time: 60
  list:
  - icon: 'minecraft:cobblestone'
    header: '&6Header'
    footer: '&7Message text #1'
  - icon: 'minecraft:apple'
    header: '&6Header'
    footer: '&7Message text #1'

# MESSAGES
messages:
  no-chat-mode: '&cApplicable chat-mode not found. You can''t send the message'
  reload: '&aConfig successful reloaded!'
  no-permission: '&cYou don''t have permission.'
  spy-on: '&aYou have been enabled spy-mode.'
  spy-off: '&cYou have been disabled spy-mode.'

