# ******************************************************
# * Chatty (version ${project.version})
#   Universal chat-system for Bukkit-server.
#   Creator: MrBrikster.
# * Optional dependencies:
#   Vault, PlaceholderAPI.
# ******************************************************

# * General settings section.
# Common settings and small features.
general:
  # Plugin localization.
  # Possible values:
  # en - English.
  # ru - Russian.
  # de - German.
  locale: en

  # Chat listener priority.
  # Possible values:
  # lowest, low, normal, high, highest.
  priority: low

  # Chat logging in "Chatty/logs".
  log: true

  # Spy-mode.
  # Permission:
  # chatty.spy.<chat>
  # or chatty.spy.
  #
  # Permission for /spy:
  # chatty.command.spy
  spy:
    # On/off spy-mode.
    enable: true
    # Spy-mode message format.
    format: '&6[Spy] &r{format}'
    # PM spy-mode message format.
    # Permission: chatty.spy
    # or chatty.spy.pm
    pm-format: '&6[Spy] &7{sender} &6-> &7{recipient}: &f{message}'

  # Private messages.
  # Permissions:
  # chatty.command.message
  # chatty.command.reply
  pm: true

# * Chats.
# There
# On the server there can be different chats with different settings,
# whether it's donate-chat, admin-chat, or the usual local and global.
#
# Permissions:
# chatty.chat.<chat> - permission for both writing and seeing messages.
# chatty.chat.<chat>.write - permission for writing messages.
# chatty.chat.<chat>.see - permission for seeing messages.
#
# Chat has the following options:
# enable - on/off chat.
# format - chat formatting string.
# range - chat range. -1 to world-wide chat, -2 to server-wide chat.
# symbol - the character from which the messages begin.
# cooldown - message cooldown in seconds (bypass permission - chatty.cooldown.<chat>).
# money - message price (depends on Vault).
# permission - should this chat use permissions? Default value is true.
chats:
  local:
    enable: true
    format: '[Local] {prefix}{player}{suffix}: {message}'
    range: 100
    cooldown: -1

  global:
    enable: true
    format: '[Global] {prefix}{player}{suffix}: {message}'
    range: -1
    symbol: '!'
    cooldown: -1

# * JSON.
# Formatting chat messages with JSON.
# 1.7.10+.
json:
  # 1.7.10+
  enable: false

  # Command that executes (by player) when you click on the player's name.
  # Supports PlaceholderAPI.
  # *** You should use "command" OR "suggest_command" OR "link" and cannot combine.
  #
  # You can use "{player}" variable here.
  command: /home

  # Command that suggests when you click on the player's name.
  # Supports PlaceholderAPI.
  # *** You should use "command" OR "suggest_command" OR "link" and cannot combine.
  #
  # You can use "{player}" variable here.
  suggest_command: '/msg {player} '

  # URL that opens when when you click on the player's name.
  # You must use "http://" or "https://" prefix, else you will crash Minecraft client :D
  #
  # Supports PlaceholderAPI.
  #
  # You can use "{player}" variable here.
  link: 'http://google.com'

  # Hover tooltip for the player's name.
  # Supports PlaceholderAPI.
  #
  # You can use "{player}" variable here.
  tooltip:
  - '&fPlayer &e{player}'
  - '&fThis tooltip supports'
  - '&fPlaceholderAPI placeholders!'

  # Replacements for chat formats
  #
  # You can replace plain text with JSON-pieces
  # to make chat more interactive.
  #
  # Available properties:
  # text, tooltip, command, suggest_command, link.
  replacements:
    '&cAdmin':
      # Text to replace.
      # You can remove this line, if you need old text.
      text: '&cAdmin'

      # Hover tooltip for the text.
      #
      # You can use "{player}" variable here.
      tooltip:
      - '&cThis is admin.'
      - '&4&lBe afraid of him!'
      - ''
      - '&eClick here to see the server rules.'

      # *** You should use "command" OR "suggest_command" OR "link" and cannot combine.
      # Command that executes when you click on the text.
      #
      # You can use "{player}" variable here.
      command: /rules

# * Notifications.
# There are three types of notifications:
# via Chat, ActionBar (1.8+) and Advancements (1.12+).
notifications:
  # Chat notifications..
  chat:
    # On/off chat notifications.
    enable: true
    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.chat.default
      default:
        # Messages interval.
        time: 60
        # Messages prefix.
        prefix: ''
        # List of messages.
        messages:
        - '&cThe server is using Chatty!'
        - '&aThe server is using Chatty!'
        # Disable permission checking.
        # Delete the line, if you need this.
        permission: false

  # ActionBar notifications.
  # It's static notifications,
  # which changes the message with interval.
  #
  # Permission: chatty.notification.actionbar
  actionbar:
    # On/off ActionBar notifications.
    # Only 1.8+.
    enable: false
    # One message time.
    time: 60
    # Messages prefix.
    prefix: ''
    # List of messages.
    messages:
    - '&cThe server is using Chatty!'
    - '&aThe server is using Chatty!'
    # Disable permission checking.
    # Delete the line, if you need this.
    permission: false

  # Advancements (Achievements) notifications.
  advancements:
    # Advancements notifications.
    # Only 1.12+.
    enable: false
    # Notification lists.
    lists:
      # List "default".
      # Permission: chatty.notification.advancements.default
      default:
        # Messages interval.
        time: 60
        # List of messages.
        messages:
        - icon: 'minecraft:diamond'
          header: '&bChatty v.${project.version}'
          footer: '&fThank you for using!'
        - icon: 'minecraft:gold_ingot'
          header: '&eChatty v.${project.version}'
          footer: '&fThank you for using!'
        # Disable permission checking.
        # Delete the line, if you need this.
        permission: false

# * Moderation.
# Automatic chat moderation tools.
moderation:
  caps:
    # On/off caps protection.
    # Bypass permission: chatty.moderation.caps
    enable: true
    # Minimal length of message to caps checking.
    length: 6
    # Minimal upper case procent for caps.
    procent: 80
    # On/off caps message blocking.
    # When false, message will be sent in lower case.
    block: true
  advertisement:
    # On/off advertisement protection.
    # Bypass permission: chatty.moderation.advertisement
    enable: true
    # Regular expressions for IP-addresses and sites.
    patterns:
      ip: '(?:\d{1,3}[.,-:;\/()=?}+ ]{1,4}){3}\d{1,3}'
      web: '[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+~#?&//=]*)?'
    # Whitelisted IP-addresses and sites.
    whitelist:
    - 'example.com'
    - 'vk.com'
    - 'google.com'
    - 'yandex.ru'
    - '192.168.1.1'
    - '127.0.0.1'
  swear:
    # On/off swear protection.
    # Bypass permission: chatty.moderation.swear
    enable: true
    # Block or remove word from message?
    block: true
    # Replacement for swears.
    replacement: '<swear>'
    # Swear-list configuration: "Chatty/swears"

# * Misc.
# Change default Minecraft messages.
misc:
  join:
    # Set '' to disable.
    message: '&e{prefix}{player}{suffix} &ejoined the server.'
    # If player doesn't have permission, message won't send.
    #
    # Permission: chatty.misc.joinmessage
    permission: false
  quit:
    # Set '' to disable.
    message: '&e{prefix}{player}{suffix} &eleft the server.'
    # If player doesn't have permission, message won't send.
    #
    # Permission: chatty.misc.quitmessage
    permission: false
  death:
    # Set '' to disable.
    message: '&e{prefix}{player}{suffix} &edied.'
    # If player doesn't have permission, message won't send.
    #
    # Permission: chatty.misc.deathmessage
    permission: false
